server:
  port: 8000
application:
  title: Mega app
foo:
  enabled: false
  ip: 192.168.1.1
  roles:
    - USER
    - ADMIN

# You can use trigger file in order to reload app only when changes to this file occur. Note: You can even specify something like
# HelloWorldController.java as a reload file.
# See pom.xml comment for more info about reload

#spring:
#  devtools:
#    restart:
#      trigger-file: .restart



