server:
  port: 8000

spring:
  application:
    name: myapp
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native  # You need to add this profile in order for config server to get configuration from local files
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:config/

#Custom properties. See learn_to_code.springboot.props.FooProperties
foo:
  enabled: false
  ip: 192.168.1.1
  roles:
    - USER
    - ADMIN

#Loggin level
logging:
  level:
    learn_to_code.springboot: DEBUG

# Other properties used here and there
queue:
  name: queue



# You can use trigger file in order to reload app only when changes to this file occur. Note: You can even specify something like
# HelloWorldController.java as a reload file.
# See pom.xml comment for more info about reload

#spring:
#  devtools:
#    restart:
#      trigger-file: .restart


