spring.datasource:
  platform: postgres
  url: jdbc:postgresql://localhost:5432/ignite
  username: pavel
  password: pavel
  driver-class-name: org.postgresql.Driver

spring.jpa:
  hibernate.ddl-auto: create-drop