spring.datasource:
  platform: postgres
  url: jdbc:postgresql://localhost:5432/postgres
  username: pavel
  password: pavel
  driver-class-name: org.postgresql.Driver

spring.jpa:
  hibernate.ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL94Dialect
      temp.use_jdbc_metadata_defaults: false
