server.port: 8000

spring.datasource:
  url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=TRUE
  username: sa
  password:
  driverClassName: org.h2.Driver
  initialization-mode: always
spring.jpa:
  hibernate.ddl-auto: create-drop
  properties.hibernate.dialect: org.hibernate.dialect.H2Dialect