global:
 scrape_interval: 15s
 evaluation_interval: 15s
rule_files: []

scrape_configs:
- job_name: my_app
  scrape_interval: 10s
  static_configs:
  - targets:
    - host.docker.internal:8001
    - host.docker.internal:8002