server.port: 8080

spring.datasource:
  url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
  username: sa
  password:
  driverClassName: org.h2.Driver
  initialization-mode: always

spring.jpa:
  hibernate.ddl-auto: create-drop
  properties.hibernate.dialect: org.hibernate.dialect.H2Dialect

spring.h2.console:
  enabled: true
  path: /h2-console

logging.level:
  org.springframework.web: DEBUG
  org.springframework.security: DEBUG
  org.hibernate: DEBUG