server:
  port: 8000
application:
  title: Mega app
foo:
  enabled: false
  ip: 192.168.1.1
  roles:
    - USER
    - ADMIN
spring:
  devtools:
    restart:
      trigger-file: HelloWorldController.java
      additional-paths: .



